CREATE TABLE COMMENT
(
    ID INT NOT NULL
    AUTO_INCREMENT,
    TITLE VARCHAR
    (32) NOT NULL,
    CATEGORY VARCHAR
    (32) NOT NULL,
    CONTENT VARCHAR
    (32) NOT NULL,
    PRIMARY KEY
    (ID)
);